name: Build ImmortalWrt
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取源码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev libncurses-dev gawk flex bison git python3 python3-pip unzip wget

      - name: 使用我们的 .config 配置
        run: |
          cp .config .config.bak
          make defconfig

      - name: 编译固件
        run: |
          make -j$(nproc) V=s

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt-4G-Router-Firmware
          path: bin/targets/ramips/mt76x8/*.bin
